import type { CloudErrorCode } from "../lib/supabase/errors";

export const HANDOFF_STATUSES = [
  "uploading",
  "sending",
  "sent",
  "received",
  "opened",
  "modified",
  "returning",
  "returned",
  "return_received",
  "revision_requested",
  "completed",
  "failed",
] as const;

export type HandoffStatus = (typeof HANDOFF_STATUSES)[number];

export const he = {
  brand: "FileRelay",
  today: "היום",
  yesterday: "אתמול",
  setupTitle: "ברוכים הבאים ל־FileRelay",
  setupQuestion: "איך להציג את המחשב הזה?",
  deviceNameLabel: "שם המחשב",
  deviceNamePlaceholder: "לדוגמה: המחשב של מאור",
  continue: "המשך",
  cancel: "ביטול",
  deviceNameRequired: "נא להזין שם למחשב",
  deviceNameTooLong: "השם ארוך מדי",
  setupHint: "אפשר לסגור את החלון. FileRelay ימשיך לפעול ליד השעון.",
  previewHeading: "תצוגה",
  previewDateLabel: "תאריך",
  previewEndpointLabel: "כתובת",
  previewFileLabel: "קובץ",
  sendFile: "שליחת קובץ",
  send: "שלח",
  recipientLabel: "נמען",
  instructionLabel: "הנחיה",
  dueOnLabel: "מועד רצוי",
  chooseRecipient: "בחירת נמען",
  waitingForMe: "מחכה לי",
  waitingForOthers: "מחכה לאחרים",
  done: "הסתיים",
  noWaitingForMe: "אין קבצים שממתינים לך",
  noWaitingForOthers: "אין קבצים שממתינים לאחרים",
  noDoneFiles: "אין העברות שהסתיימו",
  senderLabel: "שולח",
  latestVersionLabel: "גרסה {version}",
  showHistory: "הצג היסטוריה",
  hideHistory: "הסתר היסטוריה",
  approveAndComplete: "אשר וסיים",
  requestRevision: "החזר לתיקון",
  revisionNoteLabel: "הערת תיקון",
  confirmRevision: "שלח לתיקון",
  recipientRequired: "נא לבחור נמען",
  fileRequired: "נא לבחור קובץ",
  instructionTooLong: "ההנחיה ארוכה מדי",
  revisionNoteTooLong: "הערת התיקון ארוכה מדי",
  autostartLabel: "הפעל את FileRelay עם Windows",
  historySent: "נשלח",
  historyOpened: "הקובץ נפתח",
  historyModified: "הקובץ נערך",
  historyReturned: "הוחזר",
  historyReturnedVersion: "הוחזר · גרסה {version}",
  historyRevisionRequested: "הוחזר לתיקון",
  historyCompleted: "אושר והושלם",
  receivedFiles: "קבצים שהתקבלו",
  sentFiles: "קבצים שנשלחו",
  open: "פתח",
  returnFile: "החזר קובץ",
  returnFileTo: "החזר ל{name}",
  fileReturnedBy: "{name} החזירה את הקובץ",
  syncingChanges: "מסנכרן שינויים…",
  watchFailed: "לא ניתן לעקוב אחר שינויים בקובץ הזה",
  fileBusy: "לא ניתן לקרוא את הקובץ כרגע. סגור אותו ונסה שוב.",
  fileChangedDuringReturn: "הקובץ השתנה בזמן ההחזרה. נסה שוב.",
  noSentFiles: "אין קבצים שנשלחו",
  fileUpdated: "הקובץ עודכן",
  connected: "מחובר",
  disconnected: "לא מחובר",
  connecting: "מתחבר…",
  transferFailed: "ההעברה נכשלה",
  tryAgain: "נסה שוב",
  pairDevice: "חיבור מחשב",
  deviceName: "שם המחשב",
  pairingCode: "קוד חיבור",
  fileReceived: "התקבל קובץ חדש",
  returnedVersion: "התקבלה גרסה מעודכנת",
  chooseFile: "בחירת קובץ",
  settings: "הגדרות",
  exit: "יציאה",
  dropHint: "גרור קובץ לכאן",
  noWaitingFiles: "אין קבצים שממתינים לך",
  loading: "טוען…",
  readyTitle: "המחשב מוכן",
  readyBody: "השם נשמר במחשב הזה. בפעם הבאה FileRelay ייפתח ישר לכאן.",
  deviceIdLabel: "מזהה המחשב",
  saveFailed: "לא הצלחנו לשמור את ההגדרות. נסה שוב.",
  downloadAndOpen: "הורד ופתח",
  openFolder: "פתח תיקייה",
  newFileFrom: "קובץ חדש מ{name}",
  fileTooLarge: "הקובץ גדול מדי",
  sendFailed: "השליחה נכשלה",
  downloadFailed: "ההורדה נכשלה",
  hashMismatch: "הקובץ שהתקבל אינו תואם",
  cloudNotConfiguredTitle: "החיבור לענן עדיין לא הוגדר",
  cloudNotConfiguredBody: "יש להוסיף את פרטי Supabase לקובץ ההגדרות",
  cloudConnecting: "מתחבר ל־FileRelay…",
  cannotConnectNow: "לא ניתן להתחבר כרגע",
  workspaceHowToStart: "איך תרצה להתחיל?",
  createWorkspace: "צור צוות חדש",
  joinWorkspace: "הצטרף לצוות",
  joinCodeLabel: "קוד הצטרפות",
  joinCodePlaceholder: "AB12-CD34",
  joinCodeRequired: "נא להזין קוד הצטרפות",
  workspaceReadyTitle: "הצוות מוכן",
  workspaceNameLabel: "שם הצוות",
  membersLabel: "חברי הצוות",
  thisComputer: "זה המחשב הזה",
  waitingForMembers: "ממתין לחברים נוספים",
  creatingWorkspace: "יוצר צוות…",
  joiningWorkspace: "מתחבר לצוות…",
  workspaceOfPrefix: "הצוות של ",
  createNewJoinCode: "צור קוד הצטרפות חדש",
  copyJoinCode: "העתק קוד",
  copyJoinCodeFailed: "לא הצלחנו להעתיק את הקוד. נסה שוב.",
  creatingJoinCode: "יוצר קוד…",
  authStoreCorruptHint: "הנתונים הקיימים נשמרו ולא בוצע חיבור חדש",
  cloudError: {
    cloud_not_configured: "החיבור לענן עדיין לא הוגדר",
    cloud_unavailable: "לא הצלחנו להתחבר כרגע. נסה שוב בעוד רגע.",
    anonymous_auth_failed: "לא הצלחנו להתחבר. נסה שוב.",
    workspace_creation_failed: "לא הצלחנו ליצור את הצוות. נסה שוב.",
    invalid_join_code: "קוד ההצטרפות אינו תקין.",
    already_in_workspace: "כבר שייך לצוות.",
    workspace_load_failed: "לא הצלחנו לטעון את הצוות. נסה שוב.",
    members_load_failed: "לא הצלחנו לטעון את חברי הצוות. נסה שוב.",
    join_code_rotate_failed: "לא הצלחנו ליצור קוד הצטרפות חדש. נסה שוב.",
    auth_store_corrupt: "לא ניתן לקרוא את פרטי החיבור השמורים של FileRelay",
    handoff_create_failed: "לא הצלחנו להתחיל את השליחה. נסה שוב.",
    handoff_finalize_failed: "לא הצלחנו לסיים את השליחה. נסה שוב.",
    handoff_already_finalized: "הקובץ כבר נשלח.",
    handoff_object_missing: "הקובץ לא הועלה במלואו. נסה שוב.",
    handoff_object_size_mismatch: "גודל הקובץ אינו תואם. נסה שוב.",
    handoff_fail_failed: "לא הצלחנו לעדכן את מצב השליחה.",
    handoff_receive_failed: "לא הצלחנו לעדכן שהקובץ התקבל.",
    handoff_load_failed: "לא הצלחנו לטעון את הקבצים. נסה שוב.",
    handoff_open_failed: "לא הצלחנו לעדכן שהקובץ נפתח.",
    handoff_modify_failed: "לא הצלחנו לעדכן שהקובץ נערך.",
    handoff_unmodify_failed: "לא הצלחנו לעדכן שהקובץ שוחזר.",
    handoff_return_begin_failed: "לא הצלחנו להתחיל את ההחזרה. נסה שוב.",
    handoff_return_finalize_failed: "לא הצלחנו לסיים את ההחזרה. נסה שוב.",
    handoff_return_fail_failed: "לא הצלחנו לבטל את ההחזרה.",
    handoff_return_receive_failed: "לא הצלחנו לעדכן שהקובץ המעודכן התקבל.",
    instruction_required: "נא להזין הנחיה.",
    revision_note_required: "נא להזין הערת תיקון.",
    handoff_complete_failed: "לא הצלחנו לסיים את ההעברה.",
    handoff_revision_failed: "לא הצלחנו לבקש תיקון.",
    handoff_already_completed: "ההעברה כבר הסתיימה.",
    file_too_large: "הקובץ גדול מדי",
    send_failed: "השליחה נכשלה",
    download_failed: "ההורדה נכשלה",
    unsupported_inbox_schema: "פורמט תיבת הדואר המקומית אינו נתמך",
    hash_mismatch: "הקובץ שהתקבל אינו תואם",
    selection_unknown: "לא הצלחנו לקרוא את הקובץ שנבחר. נסה שוב.",
    invalid_storage_path: "לא הצלחנו לשלוח את הקובץ. נסה שוב.",
    invalid_download_url: "לא הצלחנו להוריד את הקובץ. נסה שוב.",
    file_busy: "לא ניתן לקרוא את הקובץ כרגע. סגור אותו ונסה שוב.",
    file_changed_during_return: "הקובץ השתנה בזמן ההחזרה. נסה שוב.",
    watch_failed: "לא ניתן לעקוב אחר שינויים בקובץ הזה",
    snapshot_unknown: "לא הצלחנו להכין את הקובץ להחזרה. נסה שוב.",
    unknown_cloud_error: "משהו השתבש. נסה שוב.",
  } satisfies Record<CloudErrorCode, string>,
  handoffStatus: {
    uploading: "מתחיל שליחה…",
    sending: "שולח…",
    sent: "נשלח",
    received: "הקובץ התקבל",
    opened: "הקובץ נפתח",
    modified: "הקובץ נערך",
    returning: "מחזיר…",
    returned: "הוחזר",
    return_received: "הקובץ המעודכן התקבל",
    revision_requested: "הוחזר לתיקון",
    completed: "הושלם",
    failed: "נכשל",
  } satisfies Record<HandoffStatus, string>,
} as const;

export type HebrewCopy = typeof he;

export function handoffStatusLabel(status: HandoffStatus): string {
  return he.handoffStatus[status];
}

export function cloudErrorLabel(code: CloudErrorCode): string {
  return he.cloudError[code];
}

export function newFileFromLabel(name: string): string {
  return he.newFileFrom.replace("{name}", name);
}

export function returnFileToLabel(name: string): string {
  return he.returnFileTo.replace("{name}", name);
}

export function fileReturnedByLabel(name: string): string {
  return he.fileReturnedBy.replace("{name}", name);
}

export function cloudErrorHint(code: CloudErrorCode): string | null {
  if (code === "auth_store_corrupt") {
    return he.authStoreCorruptHint;
  }
  return null;
}
